# Generated by Django 3.2.18 on 2023-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_default_published'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_questions',
            field=models.ManyToManyField(to='game.Question', verbose_name='пройденные вопросы'),
        ),
    ]
