# Generated by Django 3.2.18 on 2023-04-11 15:01

from django.db import migrations, models
import sorl.thumbnail.fields
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='По аватарке другие люди смогут вас узнавать, а вам будет проще определять, в какой аккаунт вы вошли.', null=True, upload_to='media/%Y/%m/', verbose_name='аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Количество очков.', verbose_name='очки'),
        ),
    ]
