# Generated by Django 3.2.18 on 2023-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_seen_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='баллы в сессии'),
        ),
    ]
