version: "3.3"
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    entrypoint: /app/entrypoint.sh
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    links:
      - redis
      - db
    env_file:
      - ./.env

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
  
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

volumes:
  database:
  static_value:
  media_value:
