[tool.black]
line-length = 79
skip-string-normalization = true
exclude = '''
/(
    \.git
  | __pycache__
  | migrations
  | venv
  | /whn/manage.py
  | \.github
)/
'''

[tool.djlint]
profile = 'django'
max_line_length = 79
indent = 2
use_gitignore = true
extend_exclude='email_texts'
