# Generated by Django 3.2.18 on 2023-04-13 20:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='код сессии', max_length=200, verbose_name='код')),
                ('max_users', models.PositiveSmallIntegerField(help_text='максимум игроков', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='максимум игроков')),
                ('status', models.CharField(choices=[('upcoming', 'не началась'), ('active', 'идёт'), ('ended', 'окончена')], help_text='статус комнаты', max_length=15, verbose_name='статус')),
                ('complexity', models.PositiveSmallIntegerField(choices=[(1, 'легко'), (2, 'средне'), (3, 'тяжело')], help_text='сложность заданий в сессии', verbose_name='сложность')),
                ('max_questions', models.PositiveSmallIntegerField(help_text='количество вопросов в сессии', validators=[django.core.validators.MaxValueValidator(25)], verbose_name='всего вопросов')),
                ('users', models.ManyToManyField(related_name='пользователи', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
