# Generated by Django 3.2.18 on 2023-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('upcoming', 'не началась'), ('active', 'идёт'), ('ended', 'окончена')], default='upcoming', help_text='статус комнаты', max_length=15, verbose_name='статус'),
        ),
    ]
