# Generated by Django 3.2.18 on 2023-04-16 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(default=uuid.uuid4, help_text='код сессии', max_length=200, verbose_name='код'),
        ),
    ]
