# Generated by Django 3.2.18 on 2023-04-08 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='загрузите видео', upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='видео')),
                ('score', models.PositiveIntegerField(help_text='введите очки за данный вопрос', verbose_name='очки')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('climax_second', models.PositiveSmallIntegerField(help_text='введите секунду кульминации', verbose_name='секунда кульминации')),
                ('complexity', models.PositiveSmallIntegerField(choices=[(1, 'легко'), (2, 'средне'), (3, 'сложно')], help_text='введите сложность', verbose_name='сложность')),
                ('is_published', models.BooleanField(help_text='укажите опубликоан ли вопрос', verbose_name='побуликован ли')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='введите текст варианта ответа', max_length=200, verbose_name='текст варианта ответа')),
                ('is_correct', models.BooleanField(default=False, help_text='выберете, является ли этот вариант верным', verbose_name='верный ли')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'вариант',
                'verbose_name_plural': 'варианты',
            },
        ),
    ]
