# Generated by Django 3.2.18 on 2023-04-13 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_climax_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='climax_video',
            field=models.FileField(editable=False, upload_to='video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='видео с кульминацией'),
        ),
    ]
