# Generated by Django 3.2.18 on 2023-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_climax_video_not_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, help_text='укажите опубликоан ли вопрос', verbose_name='побуликован ли'),
        ),
    ]
