# Generated by Django 3.2.18 on 2023-04-15 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_author_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(help_text='укажите автора вопроса', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.user', verbose_name='автор'),
        ),
    ]
