# Generated by Django 3.2.18 on 2023-04-15 13:03

from django.db import migrations, models


def create_normilized_labels(apps, schema_editor):
    import game.models

    for choice in game.models.Choice.objects.all():
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='label_normilized',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.RunPython(create_normilized_labels, reverse_code=migrations.RunPython.noop),
    ]
