# Generated by Django 3.2.18 on 2023-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_label_normilized_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='label_normilized',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
