# Generated by Django 3.2.18 on 2023-04-15 20:23

from django.db import migrations, models


def create_fixed_score(apps, schema_editor):
    import game.models

    for question in game.models.Question.objects.all():
        game.models.Question.save(question, update_fields=['complexity'])


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_label_normilized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(editable=False, help_text='введите очки за данный вопрос', verbose_name='очки'),
        ),
        migrations.RunPython(create_fixed_score, reverse_code=migrations.RunPython.noop),
    ]
