name: build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-prod.txt
          pip install -r requirements/requirements-test.txt
      - name: black Lint
        uses: psf/black@stable
        with:
          options: "--check --verbose"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "pep8-naming flake8-import-order flake8-quotes flake8-broken-line flake8-print"
      - name: Run Tests
        run: |
          cd whn
          python manage.py test
        env:
          DJANGO_SUPERUSER_USERNAME: test
          DJANGO_SUPERUSER_EMAIL: test@email.com
          DJANGO_SUPERUSER_PASSWORD: Hardpwd1
